### ISSUE TITLE
[Feature]: Matomo reports minor system check issues

### ISSUE THREAD

**Issue by pmig** [glasskube/operator#220]
### Problem Description

Following issues are reported by Matomo System Check:

- [x]  Max Packet Size (needs a custom my.cnf in the MariaDB resource)
- [x] Database abilities
- [x] archiving cron job
- [x] Forced SSL Connection

**Comment by kosmoz** [comment]
fixed in 8bb917f62600ad7c7b296f3f5feba4e0b651ff28
