### ISSUE TITLE
Support `hcloud` load balancers

### ISSUE THREAD

**Issue by pmig** [glasskube/operator#43]
On [`hetznercloud`](https://github.com/hetznercloud) we want support ssl termination on their managed loadbalancers for high availablity setups.

Find related docs here: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md

**Comment by kosmoz** [comment]
https://github.com/hetznercloud/hcloud-cloud-controller-manager is not an ingress controller.
