### ISSUE TITLE
[BUG]: Discord invite link expired

### ISSUE THREAD

**Issue by pmig** [glasskube/operator#437]
The link in our README.md is already expired. Maybe we can create a permanent link.

**Comment by Anefu** [comment]
Hey @pmig. May I work on this, if it hasn't been done yet?

**Comment by pmig** [comment]
hi @Anefu this issue was sadly already closed by https://github.com/glasskube/operator/pull/449

**Comment by pmig** [comment]
@Anefu maybe this issue is also a good first issue: https://github.com/glasskube/operator/issues/461 ?
