### ISSUE TITLE
Improve docs to document custom Keycloak image

### ISSUE THREAD

**Issue by pmig** [glasskube/operator#462]
We introduced custom Keycloak image functionality (https://github.com/glasskube/operator/pull/422), but didn't documented it yet. The docs should be extended.

**Comment by UtkarshUmre** [comment]
I'm interested and would like to document the custom Keycloak image functionality. Could you please guide me on whether I should extend an existing part of the documentation or create a new section for these changes?

**Comment by pmig** [comment]
Sure, the aim of this issue is to extend the crd reference of the keycloak documentation, which can be found here: https://github.com/glasskube/operator/blob/main/docs/docs/03_crd-reference/keycloak.md
