### ISSUE TITLE
Add deploy.sh parameter for Grafana Ingress and Prometheus persistence

### ISSUE THREAD

**Issue by pmig** [glasskube/operator#58]
As a user I want peristant prometheus data and a public ingress for a persitant grafana.

I suggest a data retention of 6 months.

Optionally we can research if http basic auth is possible.

**Comment by kosmoz** [comment]
The method of enabling basic authentication depends on the IngressController being used:
- [NGINX Ingress Controller](https://kubernetes.github.io/ingress-nginx/examples/auth/basic/) 
- [Traefik](https://doc.traefik.io/traefik/middlewares/http/basicauth/)
- AWS Application Load Balancer: [not possible](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html)
